apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-volume-gpucillo4016-2
spec:
  storageClassName: rook-ceph-block-tide
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi